### ISSUE TITLE
Change Logo and Add Printer Function

### ISSUE THREAD

**Issue by afrocodes** [Esri/public-information-map-template-js#12]
Can you give us the ability to change the ESRI logo? Also, can you add the printer widget?

Thanks.

**Comment by afrocodes** [comment]
Thanks for adding in the Printer Function! Very helpful.

However, when I press print, it only shows half of the map for printing. Is there a way to get the printing function to display the whole web map area for printing?

**Comment by driskull** [comment]
hey @afrocodes . That should be possible by using print templates for the print dijit.

https://developers.arcgis.com/javascript/jsapi/print-amd.html#print1

https://developers.arcgis.com/javascript/jsapi/printtemplate-amd.html

**Comment by afrocodes** [comment]
Using print templates worked! Thanks!
