### ISSUE TITLE
Default.js update

### ISSUE THREAD

**Issue by MKellyEsri** [Esri/public-information-map-template-js#32]
The following should be included in Defaults.js from line 38 so it is easier to configure:

//Go to http://www.arcgis.com/sharing/rest/content/items/df8bcc10430f48878b01c96e907a1fc3/data?f=pjson and input below the appropriate operational layer that you want to configure as swipe layer
"swipeLayer": {
	"fields": [],
	"id": ""
},

**Comment by driskull** [comment]
thanks @MKellyEsri
