### ISSUE TITLE
Twitter API places

### ISSUE THREAD

**Issue by driskull** [Esri/public-information-map-template-js#36]
Hey ESRI team,
 
We’re writing to inform you of some changes we are implementing over the next few months in order to improve the user experience when Tweets are created with location data. Some of these changes should be visible in the Twitter UI and have an effect on the Tweet payload starting today.
 
You may have noticed recent changes to the Twitter UI allowing a user to geotag their Tweet using venue data powered by Foursquare. If a user selects the Foursquare powered venue when Tweeting, the “place” section of the Tweet data payload will include the venueID, place name, and lat/long coordinates of the venue. This has significant benefits for data consumers. Place data can now be used to associate individual Tweets with specific venues. In addition, the lat/long coordinates of these venues are much more specific than the lat/long bounding boxes provided with the previous place types--neighborhood, city, or country. These non-venue places will still be available for selection in the UI and the resulting place data in the payload will be unchanged.
 
We are working on other improvements to the user experience when Tweeting with location to keep that experience consistent with our users’ expectations. As a part of these changes, the number of Tweets with the “coordinates” payload element, which is a lat/long associated with a Tweet and not a place, is expected to decrease significantly. This specific change will begin to roll out in late April. We don’t expect this change to cause any decrease in the overall number of Tweets with "place" data, including the lat/long coordinates defining the place bounding box.
 
All of these payload changes are backward compatible and will not result in any changes to the structure of the Tweet payload. You can view a sample payload of a Tweet associated with a venue to better understand these changes.

Please let me know if you have any questions regarding these changes.

**Comment by driskull** [comment]
cc @kellyhutchins I'll update my twitter code to support places.

**Comment by kellyhutchins** [comment]
@driskull cool. Let me know when you are done and I'll update my twitter template.

**Comment by driskull** [comment]
It seems as if all the place data is polygon data. Most of them are cities and states. I did see some POI places. However, they are still polygons even though they have the same bounding box location. It seems like they should be points?

I'm not sure we want to place polygons for tweets. We could just get the center of the polygon but not sure how useful that is if the place is just "California" or "Redlands". Most tweets would be at the center of the city or state.

![screen shot 2015-03-31 at 10 04 33 am](https://cloud.githubusercontent.com/assets/1231455/6924479/a6549dc6-d78d-11e4-8ce5-9c7bfe13483b.png)


thoughts?

cc @DerrickBurke @jeffbaranyi

**Comment by driskull** [comment]
@DerrickBurke @jeffbaranyi

Here are the types of places

- admin (state)
- city
- country
- neighborhood
- poi

I was thinking we would just map tweets that are POI or neighborhood. Or do you think we should map more? It seems like state and country would be way too vague to show the center of with a point.

**Comment by driskull** [comment]
An example of a neighborhood is like "union square" in SF. Then I would just get the extent of that neighborhood and get the center of that.

The POI all seem to be points even though they are shown as polygons.

**Comment by driskull** [comment]
I'm just going to go with neighborhoods and POI. others will not be added.
