### ISSUE TITLE
YouTube API v3

### ISSUE THREAD

**Issue by driskull** [Esri/public-information-map-template-js#37]
Dear YouTube Developer,

You are receiving this email because your address is associated with a project that has recently accessed the YouTube Data API (v2), which will soon be shut down. Please disregard this message if you're not associated with such a project. There won't be any further emails.

In March 2014, we announced that the v2 API would be retired on April 20, 2015, and would be shut down soon thereafter. To help you with your migration, we published the migration guide in September. Now, we'd like to provide you with more details on the v2 retirement timeline.

As of April 20, 2015, v2 API endpoints will be shut off with the following exception: We will keep the v2 versions of the comments, captions, and flagging features accessible for a grace period past the shutdown date. These features are still listed as "To be supported" in the migration guide. The grace period is designed to give you time to implement the new v3 versions of these features as they become available. In addition, the v2 API endpoint for uploading videos will also remain open during this time.

If you would like to test your application's reaction to the v2 API shutdown, point it to eol.gdata.youtube.com instead of gdata.youtube.com.

Please migrate your app to the YouTube Data API v3 at your earliest convenience to avoid any outage.

For more information please visit: YouTube Data API v2 Turndown FAQ.

If you have any questions about the YouTube Data API v2 turndown, you can reach us via the this support form. 

Regards, 

The YouTube API Team

**Comment by driskull** [comment]
Going to take 2 requests to get the lat/lon for the videos.

sample: http://youtube.github.io/geo-search-tool/search.html?q=&la=34.0127473&lo=-117.1617685&lr=10km&tw=any&cl=&sl=92373&eo=false&loo=false&cco=false&zl=11&pbt=2015-04-03T23:05:28Z

https://github.com/youtube/geo-search-tool/

**Comment by driskull** [comment]
cc @kellyhutchins any chance for a patch so we can have YouTube videos :bowtie:

**Comment by kellyhutchins** [comment]
@driskull How risky would this fix be? How many files would be affected?

**Comment by driskull** [comment]
1-2 files. (The youtube layer file and the config for API key).

Not sure how risky, If the API isnt working i guess that's risky too.

**Comment by driskull** [comment]
e784f76f405eb490ec5f7e883a3b2ce31eb288c7

**Comment by driskull** [comment]
@kellyhutchins The patch would require updating 2 files. Is this something we want to do?

**Comment by driskull** [comment]
@iwittenmyer @kellyhutchins supposedly, the v2 YouTube API will be retired today. Just in case any issues arise from users. I tested it this morning and it was still working.

**Comment by kellyhutchins** [comment]
@driskull thanks I let support know about this issue.  Is this repo updated with the fix so users can download and host locally if necessary?

**Comment by driskull** [comment]
Yep. Its in the development branch though.
