### ISSUE TITLE
Proxy Question

### ISSUE THREAD

**Issue by wspiking** [Esri/public-information-map-template-js#41]
Does anyone have any suggestions on properly setting up the proxy for deploying the PIM?  I've successfully deployed numerous wabs using the proxy, but I'm having a heck of time getting it to work with this template.  I've added my proxy url to the default.js and added the following code to my templateConfig.js, but no dice....still getting prompted for my AGO creds.

urlUtils.addProxyRule({
  urlPrefix: "organization.maps.arcgis.com",
  proxyUrl: "http://URL/proxy.ashx"
});

Any guidance or examples would be appreciated.

Thank you,

Bill

**Comment by driskull** [comment]
Hey @wspiking  make sure you set the proxyUrl in the defaults.js as well. That may be it.

**Comment by wspiking** [comment]
Thank you @driskull.  I've included the proxy url in the default.js as well.  I think I've got something incorrect in my templateConfig.js.

**Comment by wspiking** [comment]
@driskull do I even need the urlUtils.addProxyRule in my templateConfig or can it be accomplished in the default.js?

**Comment by driskull** [comment]
I think you can put it anywhere. I usually put it in the index.html JavaScript though. As long as it gets called before the map is created it should be fine.

**Comment by wspiking** [comment]
Got it.  Thank you for your help.
