### ISSUE TITLE
Basemap Widget does not use Organization's Basemap Group

### ISSUE THREAD

**Issue by pjdohertygis** [Esri/public-information-map-template-js#42]
Today @laurenmcartney and myself are building a demonstration and it appears that the **Public Information template does not "hydrate" from my ArcGIS Online organization Basemap Group**In other words, only the Esri Default basemaps show up in the application builder. 

![image](https://cloud.githubusercontent.com/assets/4256979/15129987/7d607c36-1699-11e6-81b5-cb996ca2e6e0.png)

![image](https://cloud.githubusercontent.com/assets/4256979/15130006/9fc0b502-1699-11e6-901c-266a4a26b535.png)

![image](https://cloud.githubusercontent.com/assets/4256979/15130020/b44046e6-1699-11e6-8db7-efb528272fff.png)

This is important because here in New Zealand we use local content and projection for all of our basemaps as a best practice. Is this is a bug or by design?

**Comment by driskull** [comment]
Thanks @pjdohertygis. Yes, it currently doesn't pull from the organization. I'll see if this is something we can add in an update.

**Comment by driskull** [comment]
Actually, the basemap toggle widget only supports Esri standard basemaps right now. So this might be a bigger enhancement.

**Comment by jplunkett1** [comment]
Hi there,
I have opened a support case with Esri Support, There is a wider issue if you use a non standard Esri Basemap
Esri Case #01777792 - 
Thanks
John Plunkett
