### ISSUE TITLE
not in full screen

### ISSUE THREAD

**Issue by hamidmadai** [Esri/public-information-map-template-js#44]
i created a very Simple aplication for show a map by javascript api
when i open the page in restore down mode in my browsers i have no problem.
but when i open it on maximize mode the map loads just on the half of page.
can any body help me?
this is my code:
`<html>
<head>
	<title>test</title>
	
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  
	<meta name="viewport" content="initial-scale=1, maximum-scale=1,user-scalable=no">

  <link rel="stylesheet" href="http://localhost/arcgis_js_api/library/3.15/3.15/dijit/themes/claro/claro.css"/>
  <link rel="stylesheet" href="http://localhost/arcgis_js_api/library/3.15/3.15/esri/css/esri.css" />
	
	<script type="text/javascript" src="http://localhost/arcgis_js_api/library/3.15/3.15/init.js"></script>
	
	<script>
	require ([
		  "esri/map", "esri/dijit/Scalebar", 
      "esri/layers/ArcGISDynamicMapServiceLayer",
		  "dojo/domReady!"
    ], function(
		Map, Scalebar, ArcGISDynamicMapServiceLayer
    ) {
	
	
		    var map1 = new esri.Map("mapDiv", {logo:false});
        var basemap = new ArcGISDynamicMapServiceLayer("http://localhost:6080/arcgis/rest/services/MyMapService3/MapServer");
        map1.addLayer(basemap);
		

		    var scalebar = new Scalebar({
				  map: map1,
				  scalebarUnit: "dual"
				});
				
			}
		);
  </script>

</head>

<body>

 <div id="mapDiv"
       data-dojo-type="dijit/layout/ContentPane"
       data-dojo-props="region:'center'"
       style="overflow:hidden;">
  </div>

</body>

</html>
`

**Comment by driskull** [comment]
hey @hamidmadai can you post this question on geonet? https://geonet.esri.com/

More users will be able to see it and help you there.

**Comment by hamidmadai** [comment]
no
Unfortunately i cant open my account 
im from iran and esri dosent provide services to my country
