### ISSUE TITLE
Tweets not showing up

### ISSUE THREAD

**Issue by jeffbaranyi** [Esri/public-information-map-template-js#45]
Hey Matt,

I'm having issues getting the tweets to display properly.  I keep logging in but they don't show up and it still says "Sign in to Twitter."

http://www.arcgis.com/apps/PublicInformation/index.html?appid=da323cfd6fdb47ba82736e5a601f5f87

Any thoughts or suggestions?

Thanks,

-Jeff

**Comment by driskull** [comment]
Hey @jeffbaranyi , there's a bug when a subscription layer is in the webmap. For some reason, the oAuth cookie won't be sent so it can't log in. If you remove the layer it should be working again.

We're looking into it and @sTriche is aware of it as well.

**Comment by pjdohertygis** [comment]
I am seeing this issue now as well - all browsers. Using the http://disasterresponse.maps.arcgis.com/apps/PublicInformation/index.html?appid=de7c7b077c0144149fe5f9dd7857361d

**Comment by driskull** [comment]
We have an internal issue we're using to track this.
