### ISSUE TITLE
Splash screen formatting issues

### ISSUE THREAD

**Issue by pjdohertygis** [Esri/public-information-map-template-js#46]
It seems like the splash screen could use some design enhancements or perhaps just use a similar framework to the [Web AppBuilder Splash widget](https://doc.arcgis.com/en/web-appbuilder/create-apps/widget-splash.htm)? This is important because it is the first impression the Public has of an agency map. 

Notice below the X and the outline around it overlaps with the title.
![image](https://cloud.githubusercontent.com/assets/4256979/17452679/cee6493e-5bc5-11e6-9c26-83c925d9ac17.png)

**Comment by driskull** [comment]
that's just a focus outline. I think its ok. I could turn it off but that would cause accessibility issues.
