### ISSUE TITLE
Instagram Access Token

### ISSUE THREAD

**Issue by KCSchreiber** [Esri/public-information-map-template-js#47]
Hello,

I deployed the Public Information Map on our dev webserver and am having issues with the Instagram Layer. In the Chrome Dev tools, I get the message that the Access Token is not being accepted. I have gone to Instagram's site and generated a new one. My question is, where do I put it in the Map?

Thanks!

**Comment by driskull** [comment]
hi @KCSchreiber , it needs to be placed inside the defaults.js file included in the download. There's a setting for the instagram key.

**Comment by KCSchreiber** [comment]
I have registered an app with Instagram, I entered the provided Client ID into the "instagram_key" config. I still get the error though, I looked up on Instagram how to obtain an access token and I was able to generate one through the site.

**Comment by driskull** [comment]
Hi @KCSchreiber. The issue is that Instagram is not letting all apps use their REST API anymore.

http://developers.instagram.com/post/145262544121/instagram-platform-update-effective-june-1-2016

More info there.

We are working to see how we can get our app working again.

**Comment by KCSchreiber** [comment]
Hello,

Thank you for your reply. I look forward to the issue being resolved. Will Esri announce when the issue is fixed?

Can I share your response on GeoNet and GitHub for others?

Thanks!

Chris

Christopher Schreiber

This email may contain confidential, sensitive and privileged material for the sole use
of the intended recipient. Any review or distribution by others is strictly prohibited.
If you are NOT the intended recipient, please contact the sender and delete all copies.

**Comment by driskull** [comment]
Yes, we'll announce it with a blog post and a GeoNet thread.

Sure, feel free to share.

If we aren't able to get access to the Instagram API, we may need to change the app to meet their guidelines or remove the service.

**Comment by KCSchreiber** [comment]
Matt,

Thank you!

Chris

Christopher Schreiber

This email may contain confidential, sensitive and privileged material for the sole use
of the intended recipient. Any review or distribution by others is strictly prohibited.
If you are NOT the intended recipient, please contact the sender and delete all copies.
